#!/usr/bin/env python3

import socket
from datetime import datetime

# Создаем сокет
server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Привязываем сокет к адресу и порту
server_address = ('0.0.0.0', 1303)
server_socket.bind(server_address)

# Начинаем прослушивание входящих соединений
server_socket.listen(1)

print(f"Сервер слушает на порту {server_address[1]}...")

while True:
    # Ожидаем соединение
    connection, client_address = server_socket.accept()

    try:
        print(f"Подключился клиент с адреса {client_address}")

        # Отправляем текущую дату и время клиенту
        current_time = datetime.now().strftime("%d.%m.%Y %H:%M")
        connection.sendall(current_time.encode())

    finally:
        # Закрываем соединение
        connection.close()