#!/usr/bin/env python3

import socket

# Получаем IP адрес сервера от пользователя
server_ip = input("Введите IP адрес сервера: ")

# Создаем сокет
client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Подключаемся к серверу
server_address = (server_ip, 1303)
client_socket.connect(server_address)

try:
    # Получаем и выводим данные от сервера
    data = client_socket.recv(1024)
    print(f"Получено от сервера: {data.decode()}")

finally:
    # Закрываем соединение
    client_socket.close()




